name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; else pip install sphinx sphinx-rtd-theme nbsphinx myst-parser jupyter-sphinx sphinx-copybutton; fi

      - name: Create logo placeholder
        run: |
          mkdir -p docs/source/_static/images
          # Try to install ImageMagick if not available
          sudo apt-get update && sudo apt-get install -y imagemagick || true
          # Create blue background with text - simple logo
          convert -size 200x100 xc:#3179B9 -fill white -gravity center -font Arial -pointsize 24 -annotate 0 "mohituQ" docs/source/_static/images/mohituq_logo.png || echo "Could not create logo with ImageMagick, creating empty file" && touch docs/source/_static/images/mohituq_logo.png

      - name: Build documentation
        run: |
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build/html
          branch: gh-pages
          clean: true
          
      - name: Update Pages settings
        run: |
          echo "For manual configuration, please ensure GitHub Pages settings are:"
          echo "- Source: Deploy from a branch"
          echo "- Branch: gh-pages with / (root) folder"
          echo "The site should be available at: https://github.com/[owner]/mohituQ/settings/pages" 